# This configuration can be changed from this https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
# I will be putting comments on certain places where necessary

site_name: Coders for Causes Tech Docs
site_author: Coders for Causes
site_url: https://docs.codersforcauses.org/
repo_url: https://github.com/codersforcauses/tech-docs/

author_website: https://codersforcauses.org/ # remove this if you removed the override/partial

# This uri refers to the github path to edit, change this if you branch is different in name
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: overrides # remove this if you removed the override/partial
  palette:
  - media: "(prefers-color-scheme: light)" # below here is a palette for light mode
    scheme: cfclight
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"  # below here is a palette for dark mode
    scheme: cfcdark
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

  logo: images/cfc_logo_white_circle.png
  favicon: images/cfc_logo_white_circle.png
  features: # Refer to https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
      - navigation.instant
      - navigation.tabs
      - toc.integrate
      - header.autohide
      - content.code.annotate

plugins:
  - search

# These are markdown extensions I have included that makes the documentation look nicer
# These extensions are from here https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.tabbed
  - footnotes
  - pymdownx.critic
  - attr_list
  - def_list
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - toc:
      permalink: true
      toc_depth: 2
  - codehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: octicons/globe-16
      link: https://codersforcauses.org/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/cfc_uwa/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/codersforcauses
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCp47I0qUXeGgSK0AtFJSkbQ
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/coders-for-causes/
    - icon: fontawesome/solid/paper-plane
      link: mailto:hello@codersforcauses.org


# Add google Analytics when you need it
# Remove this if you dont need it
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
# google_analytics:
#   - UA-162451015-2 
#   - auto

# This is the extra javascript included in the documentation
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js

# If you want to put extra CSS
extra_css:
  - stylesheets/extra.css

# This is where you adjust the hierarchy if the documentation
# You can erase this if you want. If you erase this, Mkdocs will alphabetically sort your documentation
nav:
- About: 
  - Overview: index.md
  - Contributions: contributions.md